// React/王/appraisal/src/components/header.js
import React, {Component} from 'react';
class Header extends Component{
    render(){
        return <div className="tit">
            <span className="span">
              <i className="icon iconfont icon-angle-left"></i>
            </span>
            <span className="mid">{this.props.children}</span>
            <i className="span"></i>
        </div>
    }
}

export default Header

// Vue/shopping-car/src/components/Header.vue
<template>
  <div class="header-wrap">
    <header>
        <a href="#"><i class="icon iconfont icon-angle-left"></i></a>
        <a href="#">订单支付</a>
        <a href="#"><i class="icon iconfont icon-xiaoxi"></i></a>
    </header>
  </div>
</template>

<script>
    export default {
    data() {
        return {

        }
    },
    components: {

    }
    }
</script>

<style scoped>
</style>
