// Vue/food/src/components/Header.vue
<template>
   <div class="header">
        <span><router-link to="/"><i class="icon iconfont icon-angle-left"></i></router-link></span>
        <slot></slot>
        <span><i class="icon iconfont icon-gengduo"></i></span>
    </div>
</template>

<script>
export default {
  data() {
    return {

    }
  },
  components: {

  }
}
</script>

<style scoped>
</style>

// React/small-fresh-evaluations/src/components/Header.js
import React,{ Component } from 'react'
import { Link } from "react-router-dom";
import '../fonts(1)/iconfont.css';

class Header extends Component{
    render(){
        return(
            <div className="headerPage">
                <span><i className="icon iconfont icon-angle-left"></i>返回</span>
                <span>新鲜智造</span>
                <span><i className="icon iconfont icon-gengduo"></i></span>
            </div>
        )
    }
}

export default Header
