// Vue/lagou/src/App.vue
<template>
   <div id="app">  
        <router-view/>
        <Foots></Foots>
   </div>
</template>

<script>
  import Foots from "@/components/foots.vue"
  export default {
    name: 'App',
    data(){
        return{
            
        }
    },
    components:{
        Foots
    }
  }
</script>

<style>
 @import url("./css/style.css");
 @import url("./fonts(1)/iconfont.css");
</style>

// React/miss-fresh/src/App.js
import React, { Component } from 'react';
import Router from './router/router'
import routerConfig from './router/router.config'
import Footer from './components/footer/Footer'
import './App.css';

class App extends Component {
  render() {
    return (
      <div className="App">
        <Router routes={routerConfig.routes}></Router>
        <footer><Footer/></footer>
      </div>
    )
  }
}

export default App;
