// Vue/food/src/components/Header.vue
<template>
   <div class="header">
        <span><router-link to="/"><i class="icon iconfont icon-angle-left"></i></router-link></span>
        <slot></slot>
        <span><i class="icon iconfont icon-gengduo"></i></span>
    </div>
</template>

<script>
export default {
  data() {
    return {

    }
  },
  components: {

  }
}
</script>

<style scoped>
</style>

// React/王/appraisal/src/components/header.js
import React, {Component} from 'react';
class Header extends Component{
    render(){
        return <div className="tit">
            <span className="span">
              <i className="icon iconfont icon-angle-left"></i>
            </span>
            <span className="mid">{this.props.children}</span>
            <i className="span"></i>
        </div>
    }
}

export default Header
